//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandDBTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Value
    {
        public int Id { get; set; }
        [RegularExpression("([a-zA-Z0-9 .&'-]+)", ErrorMessage = "Enter only alphabets and numbers of First Name")]
        public string village { get; set; }
        public Nullable<double> block { get; set; }
        public string county { get; set; }
        public Nullable<double> acreage { get; set; }
        public Nullable<double> fair_value { get; set; }
        public string user { get; set; }
        public string tenure { get; set; }
        public System.DateTime period { get; set; }
    }
}
